# Generated by Django 3.1.14 on 2022-02-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_imagemodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
    ]
